FROM ubuntu:20.04

# setup env
WORKDIR /app
USER root

# install requirements for model and api
ENV DEBIAN_FRONTEND noninteractive
COPY azure/docker/install_dependancies.sh .
RUN chmod +x install_dependancies.sh
RUN ./install_dependancies.sh
COPY azure/docker/requirements.txt .
RUN pip3 install -r requirements.txt
RUN pip3 install git+https://github.com/facebookresearch/detectron2.git


# copy api code to app
COPY azure/docker/main.py .

# copy model code to app
COPY src/model.py /app/src/model.py
COPY src/preprocess.py /app/src/preprocess.py
COPY src/utils.py /app/src/utils.py

COPY config/doc_cls_config.yaml /app/config.yaml

EXPOSE 80
CMD [ "uvicorn","main:app","--reload","--host","0.0.0.0","--port","80"]